name: Basic Checks Test
on:
  workflow_dispatch:
    inputs:
      mod_branch:
        description: Branch of the mod to use in checks
        required: true
        default: main
      snapshot:
        description: Upload a snapshot to Turbot Pipes, if set to a value other than 'none', secrets.PIPES_TOKEN must be configured on the repository.
        required: false
        default: 'public'
        type: choice
        options:
          - public
          - private
      checks:
        description: checks to run
        required: false
        default: 'all'

jobs:
  aws_tf_compliance:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v3
      - name: Steampipe Setup
        uses: turbot/steampipe-action-setup@v1.4.0
        with:
          plugin-connections: |
            connection "tf" {
              plugin = "terraform"
              paths  = [ "./tf/*.tf" ]
            }
      - name: Steampipe Checks
        uses: turbot/steampipe-action-check@7d845af8fd682cf74536df27971248c60661354a
        with:
          mod-url: https://github.com/turbot/steampipe-mod-terraform-aws-compliance
          mod-branch: ${{ inputs.mod_branch }}
          snapshot-type: ${{ inputs.snapshot }}
          pipes-token: ${{ secrets.PIPES_TOKEN }}