name: Basic Checks Test 2
on:
  workflow_dispatch

jobs:
  aws_tf_compliance:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v3
      - name: Steampipe Setup
        uses: turbot/steampipe-action-setup@v1.5.0
        with:
          plugin-connections: |
            connection "tf" {
              plugin = "terraform"
              paths  = [ "./tf/*.tf" ]
            }
      - name: Steampipe Checks
        uses: turbot/steampipe-action-check@update-check-action
        with:
          mod-url: https://github.com/turbot/steampipe-mod-terraform-aws-compliance
          snapshot-visibility: anyone_with_link
          pipes-token: ${{ secrets.PIPES_TOKEN }}