name: Basic Checks Test
on:
  workflow_dispatch:
    inputs:
      mod_branch:
        description: Branch of the mod to use in checks
        required: true
        default: main
      snapshot:
        description: leave empty or 'anyone_with_link' / 'workspace'
        required: false
      checks:
        description: checks to run
        required: false
        default: 'all'
      artifacts:
        description: comma-sep types of exports
        required: false
      additional:
        description: additional cli args/flags
        required: false

jobs:
  aws_tf_compliance:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v3
      - name: Steampipe Setup
        uses: turbot/steampipe-action-setup@v1.5.0
        with:
          plugin-connections: |
            connection "tf" {
              plugin = "terraform"
              paths  = [ "./tf/*.tf" ]
            }
      - name: Steampipe Checks
        uses: turbot/steampipe-action-check@v1
        with:
          mod-url: https://github.com/turbot/steampipe-mod-terraform-aws-compliance
          mod-branch: ${{ inputs.mod_branch }}
          pipes-snapshot-visibility: ${{ inputs.snapshot }}
          pipes-token: ${{ secrets.PIPES_TOKEN }}
          mod-checks: ${{ inputs.checks }}
          artifact-exports: ${{ inputs.artifacts }}
          additional-args: ${{ inputs.additional }}