name: CF Checks Test
on:
  workflow_dispatch
      
jobs:
  cf_checks_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v3
      - name: Steampipe Setup
        uses: turbot/steampipe-action-setup@v1.4.0
        with:
          plugin-connections: |
            connection "awscfn" {
              plugin = "awscfn"
              paths  = [ "./cf/*" ]
            }
      - name: Steampipe Checks
        uses: turbot/steampipe-action-check@69898a40f1da2182a89ee79565f92d391464a6a5
        with:
          mod-url: https://github.com/turbot/steampipe-mod-awscfn-compliance
          mod-branch: initial-commit
          