name: CLI install
on:
  workflow_dispatch

jobs:
  only_cli:
    runs-on: ubuntu-latest
    steps:
      - name: Install steampipe
        run: sudo /bin/sh -c "$(curl -fsSL https://raw.githubusercontent.com/turbot/steampipe/main/install.sh)"
      - name: Install plugin
        run: steampipe plugin install hackernews
      - name: Query
        run: steampipe query "select * from hackernews_new"
