name: GitHub Check
on:
  workflow_dispatch:

jobs:
  github-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v3
      - name: Steampipe Setup
        uses: turbot/steampipe-action-setup@v1
        with:
          plugin-connections: |
            connection "github" {
              plugin = "github"
              token  = "${{secrets.GH_PAT}}"
            }
      - name: Steampipe Checks
        uses: turbot/steampipe-action-check@v1
        with:
          mod-url: https://github.com/turbot/steampipe-mod-github-compliance
          mod-checks: benchmark.cis_supply_chain_v100