name: Local Kubernetes Compliance Test
on:
  workflow_dispatch:

jobs:
  k8s_compliance:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v3
      - name: Steampipe Setup
        uses: turbot/steampipe-action-setup@v1
        with:
          plugin-connections: |
            connection "k8s" {
              plugin = "kubernetes"
              manifest_file_paths  = [
                "./k8s/*.yaml"
              ]
              source_type = "manifest"
            }
      - name: Steampipe Checks
        uses: turbot/steampipe-action-check@v1
        with:
          mod-url: https://github.com/turbot/steampipe-mod-kubernetes-compliance
          pipes-token: ${{ secrets.PIPES_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}