name: Annotate Pull Request Test
on:
  pull_request:
    types:
      - opened
    branches:
      - 'main'
    paths:
      - tf/*

jobs:
  compliance_with_annotations:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      checks: write
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v3
      - name: Steampipe Setup
        uses: turbot/steampipe-action-setup@v1.4.0
        with:
          plugin-connections: |
            connection "tf" {
              plugin = "terraform"
              paths  = [ "./tf/*.tf" ]
            }
      - name: Steampipe Check - Terraform AWS
        uses: turbot/steampipe-action-check@grz-test
        with:
          mod-url: https://github.com/turbot/steampipe-mod-terraform-aws-compliance
          create-annotations: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          snapshot-type: "public"
          pipes-token: ${{ secrets.PIPES_TOKEN }}
