name: OpenAPI Testing
on:
  pull_request:
    types:
      - opened
    branches:
      - 'main'
    paths:
      - openapi/*

jobs:
  compliance_with_annotations:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v3
      - name: Steampipe Setup
        uses: turbot/steampipe-action-setup@v1.5.0
        with:
          plugin-connections: |
            connection "oai" {
              plugin = "openapi"
              paths  = [ "./openapi/*" ]
            }
      - name: Steampipe Check - OpenAPI Insights Controls
        uses: turbot/steampipe-action-check@update-check-action
        with:
          mod-url: https://github.com/turbot/steampipe-mod-openapi-insights
          mod-branch: initial-controls
          snapshot-visibility: anyone_with_link
          pipes-token: ${{ secrets.PIPES_TOKEN }}