name: Test Workspace
on:
  workflow_dispatch:

jobs:
  meh:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v3
      - name: Steampipe Setup
        uses: turbot/steampipe-action-setup@v1
        with:
          plugin-connections: |
            connection "aws" {
              plugin = "aws"
            }
      - name: Steampipe Checks
        uses: turbot/steampipe-action-check@v1
        with:
          mod-url: https://github.com/turbot/steampipe-mod-aws-compliance
          mod-checks: benchmark.cis_v150
          pipes-token: ${{ secrets.PIPES_TOKEN }}
          pipes-snapshot-visibility: workspace
          additional-args: '--workspace="graza/default"'